var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { 
    title: 'Drag and Drop Team Builder - Proof of Concept' , 
    coaches: [
      {id:'108',name:'Willard Patterson'},
      {id:'109',name:'Tasha Logan'},
      {id:'110',name:'Derek Murray'},
      {id:'111',name:'Beverly Padilla'},
      {id:'112',name:'Dianna Matthews'},
      {id:'113',name:'Eric Campbell'},
      {id:'114',name:'Darren Klein'},
      {id:'115',name:'Heather Wilkins'},
      {id:'116',name:'Timothy Ross'},
      {id:'117',name:'Jason Johnston'},
      {id:'118',name:'Keith Patrick'},
      {id:'119',name:'Warren Goodwin'},
      {id:'120',name:'Rudolph Aguilar'},
      {id:'121',name:'Derrick Lane'},
      {id:'122',name:'Wilbert Price'},
      {id:'123',name:'Rodolfo Pittman'},
      {id:'124',name:'Michael Sherman'},
      {id:'125',name:'Francis Washington'},
      {id:'126',name:'Richard Lynch'},
      {id:'127',name:'Karla Lambert'},
      {id:'128',name:'Gene Weber'},
      {id:'129',name:'Enrique Kennedy'},
      {id:'130',name:'Elias Ross'}
    ],
    divisions: [ 
      { name:'7-8', 
        teams:[
          {id:'01',name:'Team-01',coaches:[],players:[]},
          {id:'02',name:'Team-02',coaches:[],players:[]},
          {id:'03',name:'Team-03',coaches:[],players:[]}
        ],
        players:[ 
          {id:'001',name:'Wesley Hamilton',age:'7'},
          {id:'002',name:'Ramona Mason',age:'7'},
          {id:'003',name:'Clinton Vega',age:'7'},
          {id:'004',name:'Lela Reed',age:'7'},
          {id:'005',name:'Irma Sandoval',age:'7'},
          {id:'006',name:'Rick Santiago',age:'7'},
          {id:'007',name:'Ellis Lloyd',age:'7'},
          {id:'008',name:'Derek Medina',age:'7'},
          {id:'009',name:'Troy Pratt',age:'7'},
          {id:'010',name:'Enrique Hunter',age:'7'},
          {id:'011',name:'Angel Sanchez',age:'7'},
          {id:'012',name:'Louise Floyd',age:'8'},
          {id:'013',name:'Cornelius Sims',age:'8'},
          {id:'014',name:'Cody Hall',age:'8'},
          {id:'015',name:'Heather Johnson',age:'8'},
          {id:'016',name:'Karla Dawson',age:'8'},
          {id:'017',name:'Ashley Delgado',age:'8'},
          {id:'018',name:'Mona Barker',age:'8'},
          {id:'019',name:'Darla Robertson',age:'8'},
          {id:'020',name:'Oliver Banks',age:'8'},
          {id:'021',name:'Kent Perry',age:'8'},
          {id:'022',name:'Lorenzo Leonard',age:'8'}
        ]
      },
      { name:'9-10', 
        teams:[
          {id:'04',name:'Team-04',coaches:[],players:[]},
          {id:'05',name:'Team-05',coaches:[],players:[]},
          {id:'06',name:'Team-06',coaches:[],players:[]}
        ],
        players:[ 
          {id:'023',name:'Eileen Hill',age:'8'},
          {id:'024',name:'Nadine Peterson',age:'9'},
          {id:'025',name:'Arthur Hunter',age:'9'},
          {id:'026',name:'Grant Garza',age:'9'},
          {id:'027',name:'Rebecca Elliott',age:'9'},
          {id:'028',name:'Ismael Brooks',age:'9'},
          {id:'029',name:'Merle Higgins',age:'9'},
          {id:'030',name:'Wendy Schneider',age:'9'},
          {id:'031',name:'Gayle Bowman',age:'9'},
          {id:'032',name:'Rebecca Cunningham',age:'9'},
          {id:'033',name:'Dominick Alvarez',age:'9'},
          {id:'034',name:'Rosa Lawrence',age:'9'},
          {id:'035',name:'Amanda Tate',age:'9'}
        ]
      },
      { name:'11-12', 
        teams:[
          {id:'07',name:'Team-07',coaches:[],players:[]},
          {id:'08',name:'Team-08',coaches:[],players:[]},
          {id:'09',name:'Team-09',coaches:[],players:[]}
        ],
        players:[ 
          {id:'036',name:'Kelli Wagner',age:'10'},
          {id:'037',name:'Bobby Turner',age:'10'},
          {id:'038',name:'Shirley Powers',age:'10'},
          {id:'039',name:'Kristi Mcdonald',age:'10'},
          {id:'040',name:'Gerardo Mathis',age:'10'},
          {id:'041',name:'Faye Barrett',age:'10'},
          {id:'042',name:'Calvin Alvarez',age:'10'},
          {id:'043',name:'Marion Martinez',age:'10'},
          {id:'044',name:'Connie Schneider',age:'10'},
          {id:'045',name:'Laurence Lyons',age:'10'},
          {id:'046',name:'Jean Greene',age:'10'},
          {id:'047',name:'Clay Davidson',age:'10'},
          {id:'048',name:'Clinton Harper',age:'11'},
          {id:'049',name:'Anita Holmes',age:'11'},
          {id:'050',name:'Jose Poole',age:'11'},
          {id:'051',name:'Agnes Hubbard',age:'11'},
          {id:'052',name:'Lola Morales',age:'11'},
          {id:'053',name:'Cary Steele',age:'11'},
          {id:'054',name:'Bobbie Scott',age:'11'},
          {id:'055',name:'Clarence Chapman',age:'11'},
          {id:'056',name:'Dennis Gray',age:'11'},
          {id:'057',name:'Carrie Johnston',age:'11'},
          {id:'058',name:'Florence Russell',age:'11'},
          {id:'059',name:'Virginia Griffith',age:'11'},
          {id:'060',name:'Janice Vaughn',age:'12'},
          {id:'061',name:'Kurt Gutierrez',age:'12'},
          {id:'062',name:'Kirk Barker',age:'12'},
          {id:'063',name:'Allen Dean',age:'12'},
          {id:'064',name:'Caroline Roberson',age:'12'},
          {id:'065',name:'Marion Adams',age:'12'},
          {id:'066',name:'Tony Grant',age:'12'},
          {id:'067',name:'Steve Maldonado',age:'12'},
          {id:'068',name:'Walter Robinson',age:'12'},
          {id:'069',name:'Ada Chandler',age:'12'}
        ]
      },
      { name:'13-15', 
        teams:[
          {id:'17',name:'Team-17',coaches:[],players:[]},
          {id:'18',name:'Team-18',coaches:[],players:[]},
          {id:'19',name:'Team-19',coaches:[],players:[]}
        ],
        players:[ 
          {id:'070',name:'Hattie Welch',age:'12'},
          {id:'071',name:'Marc Underwood',age:'12'},
          {id:'072',name:'Nina Knight',age:'13'},
          {id:'073',name:'Troy Shelton',age:'13'},
          {id:'074',name:'Julio Mendez',age:'13'},
          {id:'075',name:'Cesar Carson',age:'13'},
          {id:'076',name:'Gayle Patrick',age:'13'},
          {id:'077',name:'Cynthia Coleman',age:'13'},
          {id:'078',name:'Sammy Morrison',age:'13'},
          {id:'079',name:'Jamie Bowen',age:'13'},
          {id:'080',name:'Luis Murray',age:'13'},
          {id:'081',name:'Bridget Mendez',age:'13'},
          {id:'082',name:'Rosie Anderson',age:'13'},
          {id:'083',name:'Jeannie Cain',age:'13'},
          {id:'084',name:'June Peters',age:'14'},
          {id:'085',name:'Pablo Bryan',age:'14'},
          {id:'086',name:'Paulette Mcguire',age:'14'},
          {id:'087',name:'Wilson Bates',age:'14'},
          {id:'088',name:'Kenneth Henderson',age:'14'},
          {id:'089',name:'Molly Hammond',age:'14'},
          {id:'090',name:'Mathew Mendoza',age:'14'},
          {id:'091',name:'Adrienne Alvarez',age:'14'},
          {id:'092',name:'Jeffery Mullins',age:'14'},
          {id:'093',name:'Kelli Blake',age:'14'},
          {id:'094',name:'Harold Harmon',age:'14'},
          {id:'095',name:'Franklin Long',age:'14'},
          {id:'096',name:'Glen Fisher',age:'15'},
          {id:'097',name:'Salvador Lawrence',age:'15'},
          {id:'098',name:'Mable James',age:'15'},
          {id:'099',name:'Alberta Rose',age:'15'},
          {id:'100',name:'Lana Yates',age:'15'},
          {id:'101',name:'Edgar Mathis',age:'15'},
          {id:'102',name:'Casey Powers',age:'15'},
          {id:'103',name:'Andre Roberson',age:'15'},
          {id:'104',name:'Beverly Clayton',age:'15'},
          {id:'105',name:'Alex Sanders',age:'15'},
          {id:'106',name:'Yvette Farmer',age:'15'},
          {id:'107',name:'Edwin Graves',age:'15'}
        ]
      }
    ]
  })
});

module.exports = router;
